require 'vagrant-openstack-provider'

Vagrant.configure('2') do |config|
  config.ssh.username = 'ubuntu'
  config.ssh.private_key_path = "C:\\Users\\Admin\\Desktop\\AT-07\\linux (1).pem"
  config.vm.provider :openstack do |os, override|
    os.identity_api_version = ENV['OS_IDENTITY_API_VERSION']
    os.openstack_auth_url = ENV['OS_AUTH_URL']
    os.domain_name = ENV['OS_DOMAIN_NAME']
    os.username = ENV['OS_USERNAME']
    os.password = ENV['OS_PASSWORD']
    os.tenant_name = ENV['OS_TENANT_NAME']
    os.project_name = ENV['OS_PROJECT_NAME']
    os.keypair_name = ENV['OS_KEY_PAIR_NAME']
    os.region = ENV['OS_REGION_NAME']
    os.image = ENV['OS_IMAGE']
end

config.vm.define 'linux-server-10' do |s|
  s.vm.provision "docker"
  s.vm.provision "docker_compose", compose_version:'1.23.1'
  s.vm.provider :openstack do |os, override|
    os.server_name = 'AT07EYHA01'
    os.flavor = 'f1.desktop.small'
    override.vm.synced_folder '.', '/vagrant', disabled: true
  s.vm.provision "shell", inline: <<-SHELL
    cd /opt
    sudo wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jdk-8u45-linux-x64.tar.gz"
    sudo tar -xzvf jdk-8u45-linux-x64.tar.gz
    sudo rm -rf jdk-8u45-linux-x64.tar.gz
  SHELL
  end
 end
end
