version: '3'
services:
  jenkins_server:
    image: "registry.jala.info/devops/jenkins/jenkins:2.107.3-alpine"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
  go-server:
    image: "registry.jala.info/devops/gocd/gocd-server:v18.1.0"
    ports:
      - '8153:8153'
      - '8154:8154'
  goagent:
    image: "registry.jala.info/devops/gocd/gocd-agent-alpine-3.7:v18.1.0"
    links:
      - go-server
    environment:
      GO_SERVER_URL: https://go-server:8154/go
  sonarqube:
    image: "sonarqube:5.6.6-alpine"
    ports:
      - "9000:9000"
      - "9092:9092"
    links:
      - goagent